Error creating database from model: December 20, 2024 15:15:55
unexpected character after line continuation character (create_db_models.py, line 27)